networks:
  forgejo:
    external: false

services:
  server:
    image: codeberg.org/forgejo/forgejo:${FORGEJO_IMAGE_TAG}
    container_name: forgejo
    environment:
      - USER_UID
      - USER_GID
    restart: always
    networks:
      - forgejo
    volumes:
      - ${DATA_PATH}:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '${HTTP_PORT}:3000'
      - '${SSH_PORT}:22'
